apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: e2e-nodejs
    appstudio.openshift.io/component: devfile-sample-n6d4
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: devfile-sample-n6d4
  namespace: e2e-demos-ckaz-tenant
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_nodeshift-starters_devfile-sample
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/nodeshift-starters/devfile-sample
